name: certbot-dns-netcup
version: 2.0.0
summary: Certbot DNS Authenticator plugin for netcup
description: |
  This plugin automates the process of completing a dns-01 challenge by
  creating, and subsequently removing, TXT records using the netcup CCP
  API via lexicon.

confinement: strict
grade: stable
base: core24
platforms:
  all:
    build-on: amd64
    build-for: all


parts:
  certbot-dns-netcup:
    plugin: nil
    source: .
    build-packages:
      - python3-venv
    build-snaps:
      - certbot
    override-build: |
      MAJOR=$(python3 -c 'import sys; print(sys.version_info.major)')
      MINOR=$(python3 -c 'import sys; print(sys.version_info.minor)')
      SITE_PTH=lib/python$MAJOR.$MINOR/site-packages
      SITE_DIR=$SNAPCRAFT_PART_INSTALL/$SITE_PTH

      # Avoid installing packages that will already be included in the
      # certbot snap:
      mkdir -p $SITE_DIR
      echo /snap/certbot/current/$SITE_PTH > $SITE_DIR/certbot.pth

      python3 -m venv $SNAPCRAFT_PART_INSTALL

      VENV_BASE_PACKAGES=$(ls $SITE_DIR)

      $SNAPCRAFT_PART_INSTALL/bin/python -m pip install .

      cd $SITE_DIR
      # Remove our .pth file:
      rm -f certbot.pth
      # Remove presumably unneeded .so file - to keep platform independence:
      rm -f yaml/_yaml.*.so
      # Remove presumably unneeded packages of the venv base installation:
      rm -rf $VENV_BASE_PACKAGES
    prime:
      - lib

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.12/site-packages
