name: Build and publish
on:
  push:
  pull_request:

jobs:
  build:
    name: Build and check package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with: {python-version: 3.x}

      - run: pip install build twine ruff setuptools
      - run: ruff check .
      - run: python -m build
      - run: twine check dist/*

      - uses: actions/upload-artifact@v7
        with: {name: dist, path: dist/}

  pypi:
    name: Upload to pypi.org
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with: {name: dist, path: dist/}
      - uses: pypa/gh-action-pypi-publish@release/v1

  docker:
    name: Upload docker image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    strategy:
      matrix:
        repository:
          - docker.io
          - ghcr.io

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4

      # Build images
      - uses: docker/build-push-action@v7
        name: Build amd64 image
        with:
          platforms: linux/amd64
          build-args: FROM=certbot/certbot:latest
          load: true
          tags: |
            ${{ matrix.repository }}/coldfix/certbot-dns-netcup:amd64-latest
            ${{ matrix.repository }}/coldfix/certbot-dns-netcup:amd64-${{ github.ref_name }}

      - uses: docker/build-push-action@v7
        name: Build arm64 image
        with:
          platforms: linux/arm64
          build-args: FROM=certbot/certbot:arm64v8-latest
          load: true
          tags: |
            ${{ matrix.repository }}/coldfix/certbot-dns-netcup:arm64-latest
            ${{ matrix.repository }}/coldfix/certbot-dns-netcup:arm64-${{ github.ref_name }}

      # Login
      - uses: docker/login-action@v4
        with:
          registry: ${{ matrix.repository }}
          username: coldfix
          password: ${{ matrix.repository == 'docker.io' && secrets.DOCKERHUB_TOKEN || secrets.GITHUB_TOKEN }}

      # Push single-arch images:
      - run: docker push -a ${{ matrix.repository }}/coldfix/certbot-dns-netcup
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'

      # Create and push multi-arch image "latest":
      - run: docker manifest create
                ${{ matrix.repository }}/coldfix/certbot-dns-netcup:latest
                ${{ matrix.repository }}/coldfix/certbot-dns-netcup:amd64-latest
                ${{ matrix.repository }}/coldfix/certbot-dns-netcup:arm64-latest
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'

      - run: docker manifest push ${{ matrix.repository }}/coldfix/certbot-dns-netcup:latest
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'

      # Create and push multi-arch image for release:
      - run: docker manifest create
                ${{ matrix.repository }}/coldfix/certbot-dns-netcup:${{ github.ref_name }}
                ${{ matrix.repository }}/coldfix/certbot-dns-netcup:amd64-${{ github.ref_name }}
                ${{ matrix.repository }}/coldfix/certbot-dns-netcup:arm64-${{ github.ref_name }}
        if: startsWith(github.ref, 'refs/tags/v')

      - run: docker manifest push ${{ matrix.repository }}/coldfix/certbot-dns-netcup:${{ github.ref_name }}
        if: startsWith(github.ref, 'refs/tags/v')

  snap:
    name: Upload to snapcraft.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
